services:
  web:
    build: .
    container_name: php-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - my-network
    platform: linux/arm64

  database:
    image: mysql:8.0
    container_name: php-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network
    platform: linux/arm64

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
